<?php

namespace app\admin\controller;



class Article extends Common
{
    protected $db;
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->db = new \app\admin\model\Article();
    }

    //文章列表
    public function index(){
        $list = $this->db->getAll(2);
        $this->assign('list',$list);
        return $this->fetch();
    }
    //添加文章
    public function store(){
        if(request()->isPost()){

            $res = $this->db->store(input('post.'));
            if($res['valid']){
                $this->success($res['msg'],'index');
            }else{
                $this->error($res['msg']);
            }
        }
        $cateData = (new \app\admin\model\Category())->getAll();
        $this->assign('cateData',$cateData);
        $tagData = db('tag')->select();
        $this->assign('tagData',$tagData);
        return $this->fetch();
    }
    //回收站
    public function recycle(){
        return $this->fetch();
    }
}
