<?php
namespace app\admin\controller;

class Link extends Common{
    protected $db;
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->db = new \app\admin\model\Link();
    }
    //友情链接首页
    public function index(){
        $link = db('link')->paginate(10);
        $this->assign('link',$link);
        return $this->fetch();
    }
    //添加友情链接
    public function store(){
        if(request()->isPost()){
            $res = $this->db->store(input('post.'));
            if($res['valid']){
                $this->success($res['msg'],'index');
            }else{
                $this->error($res['msg']);
            }
        }
        return $this->fetch();
    }
    //编辑友情链接
    public function edit(){
        if(request()->isPost()){
            $res = $this->db->edit(input('post.'));

            if($res['valid']){
                $this->success($res['msg'],'index');
            }else{
                $this->error($res['msg']);
            }
        }
        $link_id = input('param.link_id');
        $link = $this->db->find($link_id);
        $this->assign('link',$link);
        return $this->fetch();
    }
    //删除友情链接
    public function del(){
        $link_id = input('param.link_id');
        if(\app\admin\model\Link::destroy($link_id)){
            $this->success('删除友情链接成功','index');
        }else{
            $this->error('删除友情链接失败');
        }

    }
}