<?php

namespace app\admin\controller;


class Tag extends Common
{
    protected $db;
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->db = new \app\admin\model\Tag();
    }

    //标签首页
    public function index(){
        $tags = db('tag')->paginate(1);
        $this->assign('tags',$tags);
        return $this->fetch();

    }
    //添加标签
    public function store(){
        if(request()->isPost()){
            $res = $this->db->store(input('post.'));
            if($res['valid']){
                $this->success($res['msg'],'index');
            }else{
                $this->error($res['msg']);
            }
        }
        return $this->fetch();
    }
}
